package infrastructure

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
)

// VerifyZaloWebhookSignature checks the X-ZEvent-Signature header Zalo sends
// on every webhook call. Confirmed against current developers.zalo.me docs
// (and against a live payload, since the docs are ambiguous on this point):
// mac = sha256(appId + rawBody + timestamp + OAsecretKey), where OAsecretKey
// is the **OA Secret Key** shown on the App console's Webhook page — a
// separate value from the App Secret Key (ZALO_OA_APP_SECRET), generated by
// Zalo only after the webhook URL is first saved. appID/timestamp come from
// the JSON body itself (app_id, timestamp fields), rawBody is the exact
// request bytes. The header itself is formatted "mac=<hex>" — callers must
// strip the "mac=" prefix before passing it in as signature.
func VerifyZaloWebhookSignature(appID, rawBody, timestamp, secretKey, signature string) bool {
	sum := sha256.Sum256([]byte(appID + rawBody + timestamp + secretKey))
	expected := hex.EncodeToString(sum[:])
	// hmac.Equal is constant-time — avoids leaking timing info about how
	// much of the signature matched.
	return hmac.Equal([]byte(expected), []byte(signature))
}
