#!/bin/sh
# Manual, one-time step for the redesign/product-model cutover (see
# /Users/tranvux/.claude/plans/tender-knitting-bunny.md, Phase 3/6) — NOT
# wired into deploy.yml, run by hand right after deploy-attribute-migration.sh
# has completed on production during the freeze window.
#
# Why this exists: deploy-attribute-migration.sh's cmd/migrate-specs-to-
# attributes-v2 only re-derives attribute_definitions/product_attribute_values
# from the legacy products.specs text — it has no way to know about the
# 130-product WebSearch-verified data audit (wrong dimensions/country-of-
# origin/placeholder text fixes) that only exists as already-corrected rows
# in dev's product_attribute_values. This script replaces production's
# freshly-(re)derived rows with dev's audited ones wholesale.
#
# Why TRUNCATE + restore all 3 tables together, not just an overlay: dev and
# production each independently ran their own seed-attribute-definitions*.sql,
# so attribute_definitions.id (gen_random_uuid() default, never hardcoded in
# the seed SQL) is DIFFERENT between the two environments even for the "same"
# logical definition (e.g. "Xuất xứ"). product_attribute_values.attribute_
# definition_id and category_attribute_definitions.attribute_definition_id
# only make sense paired with the attribute_definitions.id values from the
# SAME environment they were generated in — restoring product_attribute_
# values from dev on top of production's own attribute_definitions would
# point at nonexistent/wrong rows. Truncating all 3 and restoring dev's
# fully self-consistent set (dev's own UUIDs throughout) sidesteps this
# entirely. products.id and categories.id are NOT regenerated by this —
# confirmed identical between dev and production before writing this script
# (same origin data, zero admin edits on production since the branch split),
# so the product_id/category_id foreign keys in dev's dump resolve correctly
# against production's existing products/categories rows without any
# adjustment.
#
# Usage (on the VPS, after deploy-attribute-migration.sh has run for real):
#   1. On dev: pg_dump -U elc -d elc --data-only --column-inserts \
#        -t attribute_definitions -t category_attribute_definitions \
#        -t product_attribute_values > audited_attribute_data.sql
#   2. Copy that file to the VPS.
#   3. DATABASE_DUMP=/path/to/audited_attribute_data.sql ./restore-audited-attribute-data.sh
set -eu

if [ -z "${DATABASE_DUMP:-}" ] || [ ! -f "${DATABASE_DUMP}" ]; then
  echo "restore-audited-attribute-data: set DATABASE_DUMP to the dev dump file path" >&2
  exit 1
fi

TMP_SQL=$(mktemp)
trap 'rm -f "$TMP_SQL"' EXIT

{
  echo "BEGIN;"
  echo "TRUNCATE product_attribute_values, category_attribute_definitions, attribute_definitions RESTART IDENTITY CASCADE;"
  cat "${DATABASE_DUMP}"
  echo "COMMIT;"
} > "$TMP_SQL"

echo "restore-audited-attribute-data: truncating + restoring dev's audited attribute data (single transaction, rolls back whole on any error)"
docker exec -i elc-postgres psql -U elc -d elc -v ON_ERROR_STOP=1 < "$TMP_SQL"

echo "restore-audited-attribute-data: done. Row count sanity check:"
docker exec elc-postgres psql -U elc -d elc -c "
SELECT 'attribute_definitions' t, count(*) FROM attribute_definitions
UNION ALL SELECT 'category_attribute_definitions', count(*) FROM category_attribute_definitions
UNION ALL SELECT 'product_attribute_values', count(*) FROM product_attribute_values;
"
